/* ============================================================
   ИСТОЧНИК ДАННЫХ МИРА — единственное место, которое правится руками.
   Из него `node story-map-world/src/build.js` собирает:
     story-map-world/story.json            — весь мир для Story Map (онлайн-версия грузит его сама)
     story-map-world/json/NN-<категория>.json — то же по категориям, формат «📥 Импорт идеи» Story Map
     story-map-world/md/NN-<категория>.md     — то же по категориям, для чтения и правок
   src: 'gdd'  — есть в postapocalyptic_survival_master_game_design.md (ref — раздел)
        'idea' — предложение, в документах нет
        'open' — в документах прямо «не определено», нужно решение
   ============================================================ */

const c=(v,op,value)=>({var:v,op,value});            // условие
const set=(v,value)=>({var:v,op:'set',value});         // эффект: присвоить
const add=(v,value)=>({var:v,op:'add',value});         // эффект: прибавить
const sub=(v,value)=>({var:v,op:'subtract',value});    // эффект: отнять
const when=(...all)=>({kind:'conditions',all});
const every=(hours,repeat=true,since='')=>({kind:'scheduled',afterHours:hours,sinceNode:since,repeat});
const ch=(label,target,extra={})=>Object.assign({label,target},extra);

// ---------- Мировые переменные ----------
const VARIABLES=[
  {id:'day',name:'День игры',type:'counter',start:1,min:0,max:999,src:'idea',note:'Включает фазы мира и фоновые события.'},
  {id:'shelter_water',name:'Вода в убежище, л',type:'counter',start:300,min:0,max:5000,src:'gdd',ref:'§7.5',note:'Баланс воды: производство + накопление − потребление.'},
  {id:'shelter_energy',name:'Энергия, кВт·ч',type:'counter',start:200,min:0,max:1200,src:'gdd',ref:'§8',note:'Заряд аккумуляторов убежища.'},
  {id:'shelter_food_days',name:'Еда, дней на группу',type:'counter',start:10,min:0,max:60,src:'idea',note:'Обобщённый запас еды вместо подсчёта отдельных продуктов.'},
  {id:'shelter_meds',name:'Медикаменты, ед.',type:'counter',start:3,min:0,max:20,src:'idea',note:'Условные «единицы лечения».'},
  {id:'shelter_fuel',name:'Топливо, л',type:'counter',start:20,min:0,max:200,src:'gdd',ref:'§10.6'},
  {id:'shelter_condition',name:'Состояние убежища',type:'counter',start:70,min:0,max:100,src:'idea',note:'Износ, поломки, ремонт.'},
  {id:'shelter_known',name:'Убежище обнаружено чужими',type:'flag',start:0,min:0,max:1,src:'idea',note:'Ключ к визитам, нападениям и торговле у порога.'},
  {id:'group_size',name:'Людей в группе',type:'counter',start:2,min:0,max:12,src:'gdd',ref:'§24'},
  {id:'group_morale',name:'Мораль группы',type:'counter',start:60,min:0,max:100,src:'gdd',ref:'§27, §36'},
  {id:'group_tension',name:'Напряжение в группе',type:'counter',start:10,min:0,max:100,src:'gdd',ref:'§23',note:'Ссоры, раскол, уход.'},
  {id:'noise_level',name:'Шумность игрока',type:'counter',start:0,min:0,max:100,src:'gdd',ref:'§22',note:'Угрозы реагируют на шум.'},
  {id:'world_danger',name:'Общая опасность',type:'counter',start:20,min:0,max:100,src:'gdd',ref:'§22'},
  {id:'zombie_pressure',name:'Активность зомби рядом',type:'counter',start:15,min:0,max:100,src:'gdd',ref:'§22'},
  {id:'rep_community',name:'Отношение общины',type:'counter',start:0,min:-100,max:100,src:'idea',note:'Шкала репутации в GDD не задана (§42).'},
  {id:'rep_traders',name:'Отношение торговцев',type:'counter',start:10,min:-100,max:100,src:'idea'},
  {id:'rep_raiders',name:'Отношение рейдеров',type:'counter',start:-30,min:-100,max:100,src:'idea'},
  {id:'rep_slavers',name:'Отношение работорговцев',type:'counter',start:-10,min:-100,max:100,src:'idea'},
  {id:'rep_remnant',name:'Отношение «остатков порядка»',type:'counter',start:0,min:-100,max:100,src:'idea'},
  {id:'debt_traders',name:'Долг перед торговцами',type:'counter',start:0,min:0,max:100,src:'gdd',ref:'§21 «становиться должником»'},
  {id:'player_captured',name:'Игрок в плену',type:'flag',start:0,min:0,max:1,src:'gdd',ref:'§21'},
  {id:'member_captured',name:'Член группы в плену',type:'flag',start:0,min:0,max:1,src:'gdd',ref:'§21'},
  {id:'raiders_know_poison',name:'Рейдеры знают, кто отравил воду',type:'flag',start:0,min:0,max:1,src:'idea'},
  {id:'has_vehicle',name:'Есть машина',type:'flag',start:0,min:0,max:1,src:'gdd',ref:'§8, §21 транспорт'},
  {id:'has_greenhouse',name:'Есть оранжерея',type:'flag',start:0,min:0,max:1,src:'gdd',ref:'§10.7'},
  {id:'moved_shelter',name:'Сменил основное убежище',type:'flag',start:0,min:0,max:1,src:'gdd',ref:'§3.4'}
];

// ---------- Сущности мира (режим «🌍 Мир») ----------
const ENTITIES=[
  // слои пространства
  {ref:'loc_bunker',kind:'location',name:'Бункер игрока',src:'gdd',note:'§3. Несколько жилых комнат, вода, энергия, хранение, мастерская.'},
  {ref:'loc_outskirts',kind:'location',name:'Окрестности бункера',src:'idea',note:'Буфер между бункером и трассой: вход/шлюз, первые находки, следы чужих.'},
  {ref:'loc_highway',kind:'location',name:'Главная трасса и развилки',src:'gdd',note:'§4.2. Дорога, указатели, брошенные машины.'},
  {ref:'loc_city',kind:'location',name:'Город',src:'gdd',note:'§4.2. Улицы, жилые дома, магазины, офисы, гаражи.'},
  {ref:'loc_industrial',kind:'location',name:'Окраина / промзона',src:'idea',note:'Склады, машинные, водонапорные башни.'},
  {ref:'loc_foreign',kind:'location',name:'Чужие территории',src:'gdd',note:'§3.4, §21. Другие бункеры, поселения, лагеря фракций.'},
  {ref:'loc_danger',kind:'location',name:'Опасные / заражённые зоны',src:'gdd',note:'§22.'},
  {ref:'loc_other_bunker',kind:'location',name:'Чужой бункер',src:'gdd',note:'§3.4: больше / лучше оборудован / с выжившими / заброшен.'},
  {ref:'loc_raider_camp',kind:'location',name:'Лагерь рейдеров',src:'idea'},
  {ref:'loc_water_tower',kind:'location',name:'Водонапорная башня',src:'gdd',note:'§7.2 источник воды.'},
  // фракции (архетипы)
  {ref:'f_community',kind:'faction',name:'Община',src:'gdd',note:'Выжившие в другом бункере/поселении (§3.4). Ферма, вода, ремонт.'},
  {ref:'f_traders',kind:'faction',name:'Торговцы / караван',src:'gdd',note:'Торговля и торговые маршруты (§21).'},
  {ref:'f_raiders',kind:'faction',name:'Рейдеры / банда',src:'gdd',note:'Рейдеры, банды, мародёры (§22).'},
  {ref:'f_slavers',kind:'faction',name:'Работорговцы',src:'gdd',note:'Плен и рабство (§21).'},
  {ref:'f_remnant',kind:'faction',name:'Остатки порядка',src:'idea',note:'Военные/охрана/бывшая власть: оружие, дисциплина, свои правила.'},
  {ref:'g_loners',kind:'group',name:'Одиночки и мародёры',src:'gdd',note:'Независимые NPC (§21) — источник новых членов группы.'},
  {ref:'g_player',kind:'group',name:'Группа игрока',src:'gdd',note:'§6, §24.'},
  // угрозы
  {ref:'t_zombies',kind:'group',name:'Зомби',src:'gdd',note:'§22. ❓ Количество типов не определено.'},
  {ref:'t_animals',kind:'group',name:'Опасные животные',src:'gdd',note:'§22.'},
  {ref:'t_mutants',kind:'group',name:'Мутировавшие существа',src:'gdd',note:'§22.'},
  // ресурсы
  {ref:'r_water',kind:'resource',name:'Вода',src:'gdd'},
  {ref:'r_energy',kind:'resource',name:'Энергия',src:'gdd'},
  {ref:'r_food',kind:'resource',name:'Еда',src:'gdd'},
  {ref:'r_meds',kind:'resource',name:'Медикаменты',src:'gdd'},
  {ref:'r_fuel',kind:'resource',name:'Топливо',src:'gdd'},
  // концепты
  {ref:'k_catastrophe',kind:'concept',name:'Катастрофа (что случилось с миром)',src:'open',note:'Нигде не описана: что произошло, сколько лет прошло, откуда зомби.'},
  {ref:'k_slavery',kind:'concept',name:'Плен и рабство',src:'gdd',note:'§21.'}
];

const RELATIONS=[
  {from:'loc_outskirts',type:'находится_в',to:'loc_bunker',comment:'окрестности вокруг бункера'},
  {from:'loc_other_bunker',type:'находится_в',to:'loc_foreign'},
  {from:'loc_raider_camp',type:'находится_в',to:'loc_foreign'},
  {from:'loc_water_tower',type:'находится_в',to:'loc_industrial'},
  {from:'g_player',type:'находится_в',to:'loc_bunker'},
  {from:'f_community',type:'находится_в',to:'loc_other_bunker',status:'proposed'},
  {from:'f_raiders',type:'находится_в',to:'loc_raider_camp',status:'proposed'},
  {from:'f_raiders',type:'враг_с',to:'f_community',status:'proposed'},
  {from:'f_raiders',type:'враг_с',to:'f_traders',status:'proposed'},
  {from:'f_slavers',type:'враг_с',to:'f_community',status:'proposed'},
  {from:'f_traders',type:'друг_с',to:'f_community',status:'proposed'},
  {from:'f_slavers',type:'использует',to:'k_slavery'},
  {from:'f_community',type:'производит',to:'r_food',status:'proposed',comment:'ферма'},
  {from:'f_traders',type:'владеет',to:'r_fuel',status:'proposed'},
  {from:'f_remnant',type:'владеет',to:'loc_water_tower',status:'proposed',comment:'держат источник воды'},
  {from:'t_zombies',type:'находится_в',to:'loc_danger'},
  {from:'g_loners',type:'находится_в',to:'loc_city'}
];

// ---------- События по категориям ----------
// node: {ref,title,text,type:'event'|'choice'|'background',src,gdd,source(eventSource),trigger,effects,choices,ending,tags,refs}
const CATEGORIES=[
{
  id:'story',title:'Начало и большие решения',
  intro:'Стартовый узел игры и решения, которые меняют всю партию.',
  nodes:[
    {ref:'story.game_start',title:'Первое утро в бункере',type:'choice',src:'idea',source:'system',refs:['loc_bunker','g_player'],
     trigger:{kind:'start'},text:'Двое выживших в маленьком подземном убежище. Воды на месяц, еды на десять дней. Снаружи тихо.',
     choices:[ch('Осмотреть убежище и запасы','story.inventory_check'),ch('Выйти наружу','exploration.first_exit')]},
    {ref:'story.inventory_check',title:'Ревизия запасов',type:'event',src:'gdd',gdd:'§3.1',source:'player',
     text:'Решаем, что хранить, что использовать, что ремонтировать, когда выходить наружу.',
     choices:[ch('Пора выходить','exploration.first_exit')]},
    {ref:'story.move_shelter',title:'Сменить основное убежище?',type:'choice',src:'gdd',gdd:'§3.4',source:'player',refs:['loc_other_bunker'],
     trigger:when(c('day','>=',20)),text:'Найдено место лучше нынешнего бункера. Переезд — значимое стратегическое решение: перенос запасов, риск в пути, старое убежище останется пустым.',
     choices:[ch('Переехать','story.moved',{effects:[set('moved_shelter',1),sub('shelter_food_days',3),add('group_morale',10)]}),ch('Остаться','story.stayed')]},
    {ref:'story.moved',title:'Новый дом',type:'event',src:'idea',source:'player',text:'Старый бункер пустеет — его может занять кто-то другой.',
     choices:[ch('Позже: старый бункер занят','exploration.familiar_place_changed')]},
    {ref:'story.stayed',title:'Остаёмся',type:'event',src:'idea',source:'player',text:'Найденное место может занять кто-то другой.'},
    {ref:'story.found_own_faction',title:'Своя фракция',type:'event',src:'gdd',gdd:'§21',source:'player',
     trigger:when(c('group_size','>=',8),c('group_morale','>=',60)),text:'Группа выросла настолько, что мир начинает воспринимать её как самостоятельную силу.',
     effects:[add('world_danger',5),set('shelter_known',1)]},
    {ref:'story.become_leader',title:'Возглавить чужую группу',type:'event',src:'gdd',gdd:'§21',source:'relationship',
     text:'После переворота или смерти лидера игроку предлагают возглавить чужую группу.'},
    {ref:'story.world_history',title:'Что случилось с миром',type:'event',src:'open',gdd:'§1.3',source:'location',refs:['k_catastrophe'],
     text:'❓ Игрок должен «узнать историю мира» (§1.3), но сама история катастрофы нигде не описана.'},
    {ref:'death.group_wiped',title:'Группа погибла',type:'event',src:'gdd',gdd:'§27',source:'system',
     trigger:when(c('group_size','<=',0)),text:'Смерть постоянна. Мир продолжает жить без игрока.',ending:'death'}
  ]
},
{
  id:'time',title:'Время, погода и фазы мира',
  intro:'Единое игровое время (§9). Фазы — предложение: мир «просыпается» постепенно.',
  nodes:[
    {ref:'time.new_day',title:'Новый день',type:'background',src:'gdd',gdd:'§9',source:'timer',trigger:every(24),
     effects:[add('day',1),sub('shelter_food_days',1),sub('shelter_water',10),sub('shelter_energy',5)],text:'Каждые сутки группа ест, пьёт, тратит энергию.'},
    {ref:'time.night_falls',title:'Наступает ночь',type:'background',src:'gdd',gdd:'§22',source:'timer',trigger:every(24),
     effects:[add('zombie_pressure',5)],text:'Ночью угрозы активнее, вылазки опаснее.'},
    {ref:'time.storm',title:'Буря',type:'background',src:'idea',source:'weather',trigger:every(24*9),
     effects:[add('shelter_water',150),add('world_danger',5)],text:'Сильный дождь и ветер: вода прибывает, панели под угрозой, наружу лучше не выходить.',
     choices:[ch('Панели повреждены','energy.panel_broken')]},
    {ref:'time.phase_settling',title:'Фаза «Обживание»',type:'background',src:'idea',source:'timer',trigger:every(24*7,false),
     text:'День 8. Мир начинает замечать новичков: первые торговцы и случайные гости.',
     choices:[ch('Первый караван','trade.caravan_arrives'),ch('Кто-то у двери','group.newcomer_arrives')]},
    {ref:'time.phase_noticed',title:'Фаза «Мир заметил тебя»',type:'background',src:'idea',source:'timer',trigger:every(24*30,false),
     effects:[set('shelter_known',1),add('world_danger',10)],text:'День 30. Фракции знают об убежище, растут требования.',
     choices:[ch('Требуют дань','factions.demand_tribute')]},
    {ref:'time.phase_politics',title:'Фаза «Большая политика»',type:'background',src:'idea',source:'timer',trigger:every(24*60,false),
     effects:[add('world_danger',10)],text:'День 60. Войны, союзы, большие сдвиги территорий.',
     choices:[ch('Фракции сталкиваются','factions.groups_clash')]},
    {ref:'time.seasons',title:'Сезоны и зима?',type:'event',src:'open',source:'weather',
     text:'❓ В документах нет сезонов. Зима сильно влияет на воду, еду и топливо — нужны ли они?'}
  ]
},
{
  id:'water',title:'Вода',
  intro:'Вода — ресурс внутри объектов (резервуар, бочка). Баланс: производство + накопление − потребление (§7, §10.2).',
  nodes:[
    {ref:'water.rain_fills_tank',title:'Дождь пополнил резервуар',type:'background',src:'gdd',gdd:'§37 время+вода',source:'weather',refs:['r_water'],
     trigger:every(24*3),effects:[add('shelter_water',80)],text:'Дождь → резервуар → запас.'},
    {ref:'water.drought',title:'Засуха',type:'background',src:'idea',source:'weather',trigger:every(24*25),
     text:'Долго нет дождя. Запас не пополняется, ищем воду снаружи.',choices:[ch('Запас тает','water.shortage_crisis')]},
    {ref:'water.tank_leak',title:'Резервуар потёк',type:'background',src:'gdd',gdd:'§15 износ',source:'system',trigger:every(24*14),
     effects:[sub('shelter_water',60),sub('shelter_condition',5)],text:'Износ. Пока не починим — теряем воду каждый день.',
     choices:[ch('Чинить','repair.equipment_breaks')]},
    {ref:'water.contaminated',title:'Вода загрязнилась',type:'choice',src:'gdd',gdd:'§7.3',source:'world',
     trigger:when(c('shelter_condition','<',40)),text:'Вода в запасе грязная. Пить её — риск болезни.',
     choices:[ch('Очистить (тратим топливо на кипячение)','water.ok',{effects:[sub('shelter_fuel',5)]}),
              ch('Пить как есть','health.illness_spreads',{effects:[sub('group_morale',5)]}),
              ch('Слить и искать новую','water.found_source',{effects:[sub('shelter_water',100)]})]},
    {ref:'water.ok',title:'Вода снова чистая',type:'event',src:'idea',source:'player',text:'Кризис миновал.'},
    {ref:'water.found_source',title:'Найден источник воды',type:'choice',src:'gdd',gdd:'§7.2',source:'location',refs:['loc_water_tower'],
     text:'Скважина, водонапорная башня или склад бочек. Но не чей-то ли он?',
     choices:[ch('Брать воду сразу','water.source_claimed',{effects:[add('shelter_water',200),add('noise_level',5)]}),
              ch('Сначала разведать','exploration.traces')]},
    {ref:'water.source_claimed',title:'Источник занят фракцией',type:'choice',src:'gdd',gdd:'§21',source:'faction',refs:['f_remnant'],
     text:'Фракция заняла известный источник. Теперь вода за плату или через конфликт.',
     choices:[ch('Платить','trade.debt',{effects:[add('debt_traders',10)]}),
              ch('Отбить источник','combat.watch_fight',{effects:[sub('rep_remnant',30)]}),
              ch('Искать другой','water.found_source')]},
    {ref:'water.poisoned_by_enemy',title:'Кто-то отравил наш резервуар',type:'event',src:'gdd',gdd:'§29',source:'faction',
     trigger:when(c('shelter_known','==',1),c('rep_raiders','<=',-50)),effects:[set('shelter_water',0),sub('group_morale',15)],
     text:'Запас потерян. Кто виноват — неизвестно.',choices:[ch('Искать виновных','exploration.traces'),ch('Срочно искать воду','water.found_source')]},
    {ref:'water.player_poisons',title:'Отравить чужой запас?',type:'choice',src:'gdd',gdd:'§29',source:'player',refs:['loc_raider_camp'],
     text:'У игрока есть яд и доступ к резервуару рейдеров. Количество яда зависит от объёма.',
     choices:[ch('Отравить','water.poison_outcome',{effects:[sub('rep_raiders',20)]}),ch('Не делать этого','water.ok')]},
    {ref:'water.poison_outcome',title:'Последствия отравления',type:'choice',src:'idea',source:'faction',
     text:'У рейдеров больные и мёртвые. Узнают ли они, кто это сделал?',
     choices:[ch('Узнали — охота на игрока','combat.raid_on_shelter',{effects:[set('raiders_know_poison',1),set('rep_raiders',-100)]}),
              ch('Не узнали — рейдеры слабеют','water.ok',{effects:[add('rep_community',15),sub('world_danger',10)]})]},
    {ref:'water.shortage_crisis',title:'Вода кончается',type:'event',src:'gdd',gdd:'§7.4',source:'resource_shortage',refs:['r_water'],
     trigger:when(c('shelter_water','<',50)),effects:[sub('group_morale',10),add('group_tension',10)],
     text:'Автономные NPC сами уходят искать воду в радиусе 500 м. Мораль падает.',
     choices:[ch('Срочная вылазка за водой','water.found_source'),ch('Купить у торговцев','trade.caravan_arrives')]}
  ]
},
{
  id:'energy',title:'Энергия',
  intro:'Свой энергоконтур у объектов: аккумуляторы, солнечные панели, ветряки, велогенераторы (§8).',
  nodes:[
    {ref:'energy.panel_dirty',title:'Панели загрязнились',type:'background',src:'gdd',gdd:'§8, §9 panel_cleaning',source:'timer',trigger:every(24*5),
     effects:[sub('shelter_energy',20)],text:'Производство падает, пока панели не почистят.'},
    {ref:'energy.panel_broken',title:'Панель сломана',type:'event',src:'gdd',gdd:'§8',source:'world',effects:[sub('shelter_energy',40)],
     text:'Ветер, град или нападение. Нужны ремонт и детали.',choices:[ch('Чинить','repair.equipment_breaks')]},
    {ref:'energy.battery_low',title:'Заряд почти кончился',type:'event',src:'gdd',gdd:'§8',source:'resource_shortage',refs:['r_energy'],
     trigger:when(c('shelter_energy','<',40)),text:'Свет, лампы для урожая и холодильник скоро погаснут.',
     choices:[ch('Экономить: выключить всё лишнее','energy.ok',{effects:[sub('group_morale',5)]}),
              ch('Жечь топливо в генераторе','energy.ok',{effects:[sub('shelter_fuel',10),add('shelter_energy',60),add('noise_level',15)]}),
              ch('Ничего не делать','energy.blackout')]},
    {ref:'energy.ok',title:'Энергия есть',type:'event',src:'idea',source:'player',text:'Кризис отложен.'},
    {ref:'energy.blackout',title:'Полное отключение',type:'event',src:'idea',source:'resource_shortage',
     trigger:when(c('shelter_energy','<=',0)),effects:[sub('group_morale',15),sub('shelter_food_days',2)],
     text:'Темно, холодильник отключён, еда портится, ночью страшнее.',choices:[ch('Во тьме растёт тревога','light.dark_room_fear')]},
    {ref:'energy.found_generator',title:'Найден генератор',type:'event',src:'gdd',gdd:'§8',source:'location',
     effects:[add('shelter_energy',100)],text:'Генератор, ветряк или велогенератор — новый источник энергии.'},
    {ref:'energy.light_attracts',title:'Свет из убежища заметили',type:'background',src:'idea',source:'world',
     trigger:every(24*6),text:'Ночью свет виден снаружи. Убежище перестаёт быть тайной.',
     effects:[set('shelter_known',1)],choices:[ch('Патруль проходит мимо','factions.patrol_passes')]}
  ]
},
{
  id:'food',title:'Еда и ферма',
  intro:'Еда: консервы, сырьё, готовая еда; порча со временем (§10.1). Растения — объекты мира (§10.7).',
  nodes:[
    {ref:'food.spoilage',title:'Часть еды испортилась',type:'background',src:'gdd',gdd:'§9 food_spoilage',source:'timer',trigger:every(24*7),
     effects:[sub('shelter_food_days',2)],text:'Порча идёт независимо ни от чего.'},
    {ref:'food.stash_found',title:'Тайник с консервами',type:'choice',src:'idea',source:'location',
     text:'Под полом в заброшенном доме — запас консервов. Похоже, хозяин собирался вернуться.',
     choices:[ch('Забрать всё','food.owner_returns',{effects:[add('shelter_food_days',8)]}),
              ch('Взять половину','food.ok',{effects:[add('shelter_food_days',4),add('group_morale',3)]})]},
    {ref:'food.owner_returns',title:'Хозяин тайника ищет вора',type:'event',src:'idea',source:'npc',
     text:'Через несколько дней у убежища появляется человек: он знает, кто взял его запас.',
     choices:[ch('Договориться','group.newcomer_arrives'),ch('Прогнать','combat.ambush_on_road',{effects:[add('world_danger',5)]})]},
    {ref:'food.ok',title:'Еды хватает',type:'event',src:'idea',source:'player',text:'Пока сыты.'},
    {ref:'food.hunger_crisis',title:'Еда кончается',type:'event',src:'gdd',gdd:'§36',source:'resource_shortage',refs:['r_food'],
     trigger:when(c('shelter_food_days','<',3)),effects:[sub('group_morale',10),add('group_tension',15)],
     text:'Голод. Напряжение растёт, кто-то начинает таскать еду тайком.',
     choices:[ch('Кража внутри группы','food.theft_inside'),ch('Купить еду','food.trade_offer'),ch('Искать тайники','food.stash_found')]},
    {ref:'food.theft_inside',title:'Кто-то ворует еду',type:'choice',src:'gdd',gdd:'§36 пример',source:'npc',
     text:'Кража → NPC заметил → доверие ↓ → конфликт.',
     choices:[ch('Поговорить с виновным','group.quarrel',{effects:[add('group_tension',5)]}),
              ch('Выгнать','group.exile',{effects:[sub('group_size',1),add('group_morale',-5)]}),
              ch('Закрыть глаза','food.ok',{effects:[add('group_tension',10)]})]},
    {ref:'food.trade_offer',title:'Торговцы предлагают еду',type:'event',src:'gdd',gdd:'§21',source:'faction',refs:['f_traders'],
     text:'Обмен на воду, медикаменты или детали.',
     choices:[ch('Обменять воду на еду','food.ok',{effects:[sub('shelter_water',80),add('shelter_food_days',6),add('rep_traders',5)]}),
              ch('Взять в долг','trade.debt',{effects:[add('shelter_food_days',6),add('debt_traders',15)]})]},
    {ref:'farming.first_harvest',title:'Первый урожай',type:'event',src:'gdd',gdd:'§10.7',source:'system',
     trigger:when(c('has_greenhouse','==',1)),effects:[add('shelter_food_days',5),add('group_morale',10)],text:'Еда становится возобновляемой.'},
    {ref:'farming.crop_failed',title:'Урожай погиб',type:'event',src:'idea',source:'system',
     trigger:when(c('has_greenhouse','==',1),c('shelter_energy','<',20)),effects:[sub('group_morale',5)],
     text:'Нет света, воды или ухода. Ферма зависит от энергии и воды.'}
  ]
},
{
  id:'health',title:'Здоровье и смерть',
  intro:'Единая система здоровья: травмы, болезни, инфекции, лечение через действия (§26). Смерть постоянна и оставляет след (§27).',
  nodes:[
    {ref:'health.injury_on_raid',title:'Травма на вылазке',type:'choice',src:'gdd',gdd:'§26',source:'world',
     text:'Эффективность падает, нужно лечение.',
     choices:[ch('Лечить своими медикаментами','health.recovered',{requires:[c('shelter_meds','>=',1)],effects:[sub('shelter_meds',1)]}),
              ch('Перевязать как есть','health.infection')]},
    {ref:'health.recovered',title:'Поправился',type:'event',src:'idea',source:'system',text:'Время восстановления прошло.'},
    {ref:'health.infection',title:'Рана воспалилась',type:'choice',src:'gdd',gdd:'§26',source:'system',
     text:'Без антибиотиков — ухудшение вплоть до смерти.',
     choices:[ch('Найти лекарства','health.no_meds'),ch('Ждать и надеяться','death.member_died',{effects:[sub('group_size',1)]})]},
    {ref:'health.illness_spreads',title:'Болезнь в группе',type:'choice',src:'idea',source:'system',
     text:'Болезнь переходит на других. Карантин? Кого лечить первым?',
     choices:[ch('Карантин','health.recovered',{effects:[add('group_tension',10)]}),
              ch('Лечить всех','health.no_meds',{effects:[sub('shelter_meds',3)]})]},
    {ref:'health.no_meds',title:'Лекарства кончились',type:'event',src:'gdd',gdd:'§10.3',source:'resource_shortage',refs:['r_meds'],
     trigger:when(c('shelter_meds','<=',0)),text:'Идти за ними, просить или торговать.',
     choices:[ch('Аптека в городе','exploration.house_states'),ch('Попросить у общины','factions.first_contact'),ch('Встретить врача','health.doctor_found')]},
    {ref:'health.doctor_found',title:'Встречен врач',type:'choice',src:'gdd',gdd:'§24',source:'npc',
     text:'Человек с навыком медицины. Присоединится ли он и на каких условиях?',
     choices:[ch('Принять в группу','group.newcomer_arrives',{effects:[add('group_size',1)]}),ch('Только вылечить раненого','health.recovered',{effects:[sub('shelter_food_days',2)]})]},
    {ref:'death.member_died',title:'Член группы погиб',type:'event',src:'gdd',gdd:'§27',source:'system',
     effects:[sub('group_morale',20),add('group_tension',10)],text:'Остаются тело и вещи. Близкие реагируют сильно, малознакомые — слабо.',
     choices:[ch('Что делать с телом','death.body_decision'),ch('Реакция близкого друга','death.close_friend_reaction')]},
    {ref:'death.body_decision',title:'Что делать с телом',type:'choice',src:'gdd',gdd:'§27',source:'player',
     text:'❓ Эффекты похорон, разложения и сожжения не заданы (§42).',
     choices:[ch('Похоронить','health.recovered',{effects:[add('group_morale',5)]}),
              ch('Сжечь','health.recovered',{effects:[add('noise_level',10)]}),
              ch('Обыскать и оставить','health.recovered',{effects:[sub('group_morale',5)]})]},
    {ref:'death.close_friend_reaction',title:'Близкий друг в шоке',type:'choice',src:'gdd',gdd:'§23, §27',source:'relationship',
     text:'Отказ работать, уход из группы, злость на игрока.',
     choices:[ch('Дать время','health.recovered'),ch('Он уходит','group.desertion',{effects:[sub('group_size',1)]})]},
    {ref:'death.stranger_body_found',title:'Тело незнакомца',type:'choice',src:'gdd',gdd:'§25, §27',source:'location',
     text:'Тело с вещами. Чьё это? Кто его убил?',
     choices:[ch('Обыскать','food.ok',{effects:[add('shelter_meds',1)]}),ch('Искать следы убийцы','exploration.traces')]}
  ]
},
{
  id:'exploration',title:'Исследование, лут и переходы',
  intro:'Мир физический: игрок сам идёт, переходы через двери, края, лестницы, указатели (§4). Места меняют состояние (§18).',
  nodes:[
    {ref:'exploration.first_exit',title:'Первый выход наружу',type:'choice',src:'idea',source:'player',refs:['loc_outskirts'],
     effects:[add('noise_level',5)],text:'Окрестности бункера: тишина, следы на земле, указатель вдали.',
     choices:[ch('К дороге','exploration.signpost'),ch('Идти по следам','exploration.traces'),ch('Обыскать ближний дом','exploration.house_states')]},
    {ref:'exploration.signpost',title:'Указатель на развилке',type:'choice',src:'gdd',gdd:'§4.2',source:'location',refs:['loc_highway'],
     text:'Новое направление: город или промзона.',
     choices:[ch('В город','exploration.house_states'),ch('В промзону','water.found_source'),ch('Машина у обочины','exploration.vehicle_found')]},
    {ref:'exploration.house_states',title:'Дом: в каком он состоянии',type:'choice',src:'gdd',gdd:'§18',source:'location',refs:['loc_city'],
     text:'Обычный, ограбленный, покинутый в спешке, частично разрушенный, недавно покинутый, занятый выжившими.',
     choices:[ch('Недавно покинут','exploration.recently_left'),ch('Заперт','exploration.locked_door'),
              ch('Уже ограблен','loot.someone_else_looted'),ch('Тайник','food.stash_found'),ch('Тело внутри','death.stranger_body_found')]},
    {ref:'exploration.recently_left',title:'Еда ещё тёплая',type:'choice',src:'gdd',gdd:'§18',source:'location',
     text:'Место «недавно покинуто». Кто-то рядом. Друг или враг?',
     choices:[ch('Подождать хозяев','group.newcomer_arrives'),ch('Уйти тихо','exploration.ok'),ch('Забрать всё','combat.ambush_on_road',{effects:[add('shelter_food_days',3)]})]},
    {ref:'exploration.ok',title:'Вернулись домой',type:'event',src:'idea',source:'player',text:'Вылазка закончилась без происшествий.'},
    {ref:'exploration.traces',title:'Следы чужого присутствия',type:'event',src:'gdd',gdd:'§22',source:'world',
     text:'Угрозы и люди оставляют следы — и сами идут по следам игрока.',
     choices:[ch('Следы ведут к лагерю','factions.first_contact'),ch('Следы зомби','combat.zombies_drawn_by_noise')]},
    {ref:'exploration.locked_door',title:'Запертая дверь',type:'choice',src:'gdd',gdd:'§13, §31 break_door',source:'player',
     text:'Взломать (шумно) или искать ключ (долго).',
     choices:[ch('Взломать','exploration.ok',{effects:[add('noise_level',20)]}),ch('Искать ключ','exploration.ok')]},
    {ref:'exploration.other_bunker',title:'Найден другой бункер',type:'choice',src:'gdd',gdd:'§3.4, §41',source:'location',refs:['loc_other_bunker'],
     trigger:when(c('day','>=',10)),text:'Больше, лучше оборудован, с выжившими или заброшен.',
     choices:[ch('Там живёт группа','factions.first_contact'),ch('Пустой — занять?','story.move_shelter')]},
    {ref:'exploration.vehicle_found',title:'Найдена машина',type:'event',src:'gdd',gdd:'§8, §21',source:'location',
     effects:[set('has_vehicle',1)],text:'Транспорт: свой энергоконтур/топливо, своё хранилище.'},
    {ref:'exploration.familiar_place_changed',title:'Знакомое место изменилось',type:'background',src:'gdd',gdd:'§1.2',source:'world',
     trigger:every(24*10),text:'Знакомый дом заняли, сожгли или разграбили. Мир не ждёт игрока.'},
    {ref:'loot.someone_else_looted',title:'Кто-то успел первым',type:'event',src:'idea',source:'npc',
     text:'Место, которое игрок не успел обыскать, уже ограблено.'},
    {ref:'exploration.fast_travel_unlocked',title:'Быстрое перемещение',type:'event',src:'open',gdd:'§4.3',source:'system',
     text:'❓ Правила fast travel не определены. Первое прохождение должно быть физическим.'}
  ]
},
{
  id:'factions',title:'Фракции и торговля',
  intro:'Фракции живут без игрока: добывают, торгуют, воюют, раскалываются, меняют лидеров (§21).',
  nodes:[
    {ref:'factions.patrol_passes',title:'Патруль у убежища',type:'background',src:'gdd',gdd:'§21 патрулировать',source:'faction',trigger:every(24*4),
     text:'Патруль проходит мимо. Если убежище известно — заходит.',choices:[ch('Гости у двери','factions.visitors_at_door')]},
    {ref:'factions.groups_clash',title:'Две группы столкнулись',type:'background',src:'gdd',gdd:'§21 пример',source:'faction',trigger:every(24*8),
     text:'Встретились на ресурсах: бой, торговля или договор. Отношения между ними меняются.',
     choices:[ch('Игрок видит бой','combat.watch_fight')]},
    {ref:'factions.territory_taken',title:'Территория захвачена',type:'background',src:'gdd',gdd:'§21',source:'faction',trigger:every(24*15),
     effects:[add('world_danger',5)],text:'Знакомое место теперь чужое.',choices:[ch('Это видно на месте','exploration.familiar_place_changed')]},
    {ref:'factions.camp_abandoned',title:'Лагерь брошен',type:'event',src:'gdd',gdd:'§21',source:'faction',
     text:'Фракция ушла. Лагерь можно занять или разграбить.',choices:[ch('Разграбить','food.ok',{effects:[add('shelter_fuel',20)]}),ch('Занять','story.move_shelter')]},
    {ref:'factions.leader_changed',title:'Сменился лидер',type:'background',src:'gdd',gdd:'§21',source:'faction',trigger:every(24*20),
     text:'Переворот или смерть лидера. Отношение к игроку может перевернуться.',choices:[ch('Новый лидер зовёт поддержать его','factions.internal_coup')]},
    {ref:'factions.split',title:'Фракция раскололась',type:'event',src:'gdd',gdd:'§21',source:'faction',
     text:'Появилась новая группа, часть людей ищет новый дом.',choices:[ch('Беженцы просят приюта','factions.ask_refuge')]},
    {ref:'factions.prisoners_sold',title:'Работорговцы продали пленных',type:'background',src:'gdd',gdd:'§21',source:'faction',refs:['f_slavers'],
     trigger:every(24*12),text:'Знакомый NPC может оказаться в рабстве.',choices:[ch('Рынок рабов','capture.slave_market')]},
    {ref:'factions.shortage',title:'У фракции дефицит',type:'event',src:'gdd',gdd:'§21 потребности',source:'resource_shortage',
     text:'У фракции кончаются вода или еда — она становится агрессивнее или идёт торговать.',
     choices:[ch('Идут отнимать','combat.raid_on_shelter'),ch('Идут торговать','trade.caravan_arrives')]},
    {ref:'factions.first_contact',title:'Первая встреча с фракцией',type:'choice',src:'gdd',gdd:'§21',source:'faction',refs:['f_community'],
     text:'Тон отношений на всю дальнейшую игру.',
     choices:[ch('Мирно, предложить обмен','trade.caravan_arrives',{effects:[add('rep_community',10)]}),
              ch('Настороженно, не раскрывать убежище','exploration.ok'),
              ch('Показать силу','combat.watch_fight',{effects:[sub('rep_community',15)]})]},
    {ref:'factions.visitors_at_door',title:'Фракция пришла к убежищу',type:'choice',src:'gdd',gdd:'§21',source:'faction',
     trigger:when(c('shelter_known','==',1)),text:'«Встречать фракцию, которая сама пришла на территорию игрока».',
     choices:[ch('Выслушать','factions.demand_tribute'),ch('Не открывать','combat.raid_on_shelter',{effects:[add('world_danger',5)]})]},
    {ref:'factions.demand_tribute',title:'Требуют дань',type:'choice',src:'gdd',gdd:'§21 выдвигать требования',source:'faction',refs:['f_raiders'],
     text:'Заплатить, отказаться, торговаться или драться.',
     choices:[ch('Заплатить','factions.tribute_paid',{effects:[sub('shelter_food_days',4),sub('shelter_water',100),add('rep_raiders',10)]}),
              ch('Отказаться','combat.raid_on_shelter',{effects:[sub('rep_raiders',20)]}),
              ch('Просить защиты у другой фракции','factions.offer_alliance')]},
    {ref:'factions.tribute_paid',title:'Дань уплачена',type:'event',src:'idea',source:'faction',effects:[sub('group_morale',10)],
     text:'Пока тихо. Через неделю придут снова — и попросят больше.'},
    {ref:'factions.offer_alliance',title:'Предложение союза',type:'choice',src:'gdd',gdd:'§21',source:'faction',refs:['f_remnant'],
     text:'Защита в обмен на обязательства: часть ресурсов, люди на патрули, подчинение правилам.',
     choices:[ch('Согласиться','factions.task_given',{effects:[add('rep_remnant',20),sub('world_danger',10)]}),ch('Отказаться','exploration.ok')]},
    {ref:'factions.task_given',title:'Задание от фракции',type:'choice',src:'gdd',gdd:'§21',source:'faction',
     text:'Выполнить, провалить, выполнить частично или отказаться.',
     choices:[ch('Выполнить','exploration.ok',{effects:[add('rep_remnant',10)]}),ch('Сорвать договор','factions.broken_deal')]},
    {ref:'factions.broken_deal',title:'Договор нарушен',type:'event',src:'gdd',gdd:'§21',source:'player',effects:[sub('rep_remnant',40)],
     text:'Репутация падает, фракция может начать охоту на игрока.',choices:[ch('Охота','combat.ambush_on_road')]},
    {ref:'factions.ask_refuge',title:'Просят убежища',type:'choice',src:'gdd',gdd:'§21',source:'npc',
     text:'Ещё рты, но и ещё руки.',
     choices:[ch('Принять','group.newcomer_arrives',{effects:[add('group_size',2),sub('shelter_food_days',2)]}),ch('Отказать','exploration.ok',{effects:[sub('group_morale',5)]})]},
    {ref:'factions.internal_coup',title:'Переворот: выбери сторону',type:'choice',src:'gdd',gdd:'§21',source:'faction',
     text:'Внутри фракции борьба за власть, обе стороны просят поддержки.',
     choices:[ch('Поддержать старого лидера','exploration.ok',{effects:[add('rep_community',15)]}),ch('Поддержать заговорщиков','story.become_leader')]},
    {ref:'factions.provoke_war',title:'Стравить две фракции',type:'event',src:'gdd',gdd:'§21',source:'player',
     effects:[sub('rep_raiders',10),add('world_danger',10)],text:'Пока они воюют друг с другом, им не до игрока.',choices:[ch('Война','factions.groups_clash')]},
    {ref:'factions.mediate_peace',title:'Помирить фракции',type:'event',src:'gdd',gdd:'§21',source:'player',
     effects:[add('rep_community',10),add('rep_traders',10),sub('world_danger',10)],text:'Посредничество в переговорах.'},
    {ref:'trade.caravan_arrives',title:'Пришёл караван',type:'choice',src:'gdd',gdd:'§21',source:'faction',refs:['f_traders'],
     trigger:every(24*6),text:'Обмен ресурсов; цены зависят от дефицита.',
     choices:[ch('Купить еду','food.trade_offer'),ch('Купить топливо','exploration.ok',{effects:[sub('shelter_water',60),add('shelter_fuel',30)]}),
              ch('Взять в долг','trade.debt')]},
    {ref:'trade.debt',title:'Долг',type:'event',src:'gdd',gdd:'§21 становиться должником',source:'faction',effects:[add('debt_traders',10)],
     text:'Срок, проценты, последствия неуплаты.',choices:[ch('Срок вышел','trade.debt_due')]},
    {ref:'trade.debt_due',title:'Пора платить',type:'choice',src:'idea',source:'faction',trigger:when(c('debt_traders','>=',30)),
     text:'Торговцы пришли за долгом.',
     choices:[ch('Отдать','exploration.ok',{effects:[set('debt_traders',0),sub('shelter_water',150)]}),
              ch('Не платить','capture.member_captured',{effects:[sub('rep_traders',40)]})]},
    {ref:'trade.route_cut',title:'Маршрут перерезан бандой',type:'background',src:'gdd',gdd:'§21',source:'faction',trigger:every(24*18),
     text:'Караваны не приходят, товары дорожают или пропадают.'}
  ]
},
{
  id:'capture',title:'Плен и рабство',
  intro:'В GDD это расписано подробно: захват, плен, продажа, обмен, выкуп, побег, рабство (§21).',
  nodes:[
    {ref:'capture.player_captured',title:'Игрок в плену',type:'choice',src:'gdd',gdd:'§21',source:'faction',refs:['k_slavery','f_slavers'],
     effects:[set('player_captured',1)],text:'Плен, рабство, продажа, обмен, выкуп, побег, спасение NPC, принудительная работа, смерть.',
     choices:[ch('Бежать','exploration.ok',{effects:[set('player_captured',0),add('world_danger',5)]}),
              ch('Ждать выкупа от группы','capture.ransom',{requires:[c('group_size','>=',2)]}),
              ch('Работать на хозяев','capture.forced_labor'),
              ch('Погибнуть при попытке','death.group_wiped',{effects:[sub('group_size',1)]})]},
    {ref:'capture.ransom',title:'Выкуп',type:'event',src:'gdd',gdd:'§21',source:'faction',
     effects:[set('player_captured',0),sub('shelter_water',200),sub('shelter_food_days',5)],text:'Группа отдаёт запасы.'},
    {ref:'capture.forced_labor',title:'Принудительная работа',type:'event',src:'gdd',gdd:'§21',source:'faction',
     effects:[sub('group_morale',10)],text:'Дни проходят в работе на чужих. Можно узнать их лагерь изнутри.'},
    {ref:'capture.member_captured',title:'Захвачен член группы',type:'choice',src:'gdd',gdd:'§21',source:'faction',
     effects:[set('member_captured',1),sub('group_size',1)],text:'Выкупить, отбить, обменять или смириться.',
     choices:[ch('Выкупить','capture.ransom',{effects:[set('member_captured',0),add('group_size',1)]}),
              ch('Отбить силой','combat.raid_on_shelter',{effects:[sub('rep_slavers',30)]}),
              ch('Смириться','death.close_friend_reaction',{effects:[sub('group_morale',20)]})]},
    {ref:'capture.slave_market',title:'Рынок рабов',type:'choice',src:'gdd',gdd:'§21',source:'faction',refs:['f_slavers'],
     text:'Среди пленных — бывший член группы игрока.',
     choices:[ch('Выкупить','trade.debt',{effects:[add('group_size',1),add('debt_traders',20)]}),
              ch('Освободить силой','combat.watch_fight',{effects:[sub('rep_slavers',40),add('rep_community',15)]}),
              ch('Пройти мимо','exploration.ok',{effects:[sub('group_morale',15)]})]},
    {ref:'capture.take_prisoner',title:'Игрок взял пленного',type:'choice',src:'gdd',gdd:'§21',source:'player',
     text:'Допросить, отпустить, обменять, продать, принять в группу.',
     choices:[ch('Допросить','exploration.traces'),ch('Отпустить','exploration.ok',{effects:[add('rep_raiders',5)]}),
              ch('Продать работорговцам','exploration.ok',{effects:[add('rep_slavers',10),sub('group_morale',10)]}),
              ch('Принять в группу','group.newcomer_arrives',{effects:[add('group_size',1)]})]},
    {ref:'capture.escaped_slave',title:'Беглый раб у двери',type:'choice',src:'idea',source:'npc',trigger:when(c('day','>=',15)),
     text:'К убежищу прибежал беглец. За ним идут.',
     choices:[ch('Укрыть','group.newcomer_arrives',{effects:[add('group_size',1),sub('rep_slavers',20)]}),
              ch('Выдать','exploration.ok',{effects:[add('rep_slavers',10),sub('group_morale',10)]})]}
  ]
},
{
  id:'ai',title:'Группа и отношения',
  intro:'Любой NPC может стать членом группы (§24). Отношения влияют на доверие, лояльность, предательство, раскол (§23).',
  nodes:[
    {ref:'group.newcomer_arrives',title:'Новый человек',type:'choice',src:'gdd',gdd:'§24',source:'npc',refs:['g_loners'],
     text:'Пришёл сам или встречен в пути. Принять, проверить или прогнать.',
     choices:[ch('Принять','group.ok',{effects:[add('group_size',1),sub('shelter_food_days',1)]}),
              ch('Испытательный срок','group.betrayal'),ch('Прогнать','exploration.ok')]},
    {ref:'group.ok',title:'В группе спокойно',type:'event',src:'idea',source:'relationship',text:'Пока все ладят.'},
    {ref:'group.quarrel',title:'Ссора',type:'background',src:'gdd',gdd:'§23',source:'relationship',
     trigger:when(c('group_tension','>=',40)),effects:[add('group_tension',10),sub('group_morale',5)],text:'Двое не могут ужиться.',
     choices:[ch('Помирить','group.ok',{effects:[sub('group_tension',15)]}),ch('Раскол','group.split')]},
    {ref:'group.romance',title:'Двое сближаются',type:'background',src:'idea',source:'relationship',trigger:every(24*20),
     effects:[add('group_morale',10)],text:'Уровень «любимый человек» (§23). Смерть одного ударит по другому сильнее всего.'},
    {ref:'group.refuses_order',title:'Отказ выполнять приказ',type:'event',src:'gdd',gdd:'§23',source:'npc',
     trigger:when(c('group_morale','<',30)),effects:[add('group_tension',10)],text:'Низкая лояльность.'},
    {ref:'group.desertion',title:'Ушёл ночью',type:'event',src:'gdd',gdd:'§23',source:'npc',
     trigger:when(c('group_morale','<',20)),effects:[sub('group_size',1),sub('shelter_food_days',2)],text:'Член группы ушёл — и, кажется, с вещами.',
     choices:[ch('Позже он вернётся','group.former_member_returns')]},
    {ref:'group.betrayal',title:'Предательство',type:'event',src:'gdd',gdd:'§23',source:'npc',
     effects:[set('shelter_known',1),sub('group_morale',15)],text:'Член группы сливает информацию об убежище фракции.',
     choices:[ch('Изгнать','group.exile')]},
    {ref:'group.split',title:'Группа раскололась',type:'event',src:'gdd',gdd:'§23',source:'relationship',
     effects:[sub('group_size',2),set('group_tension',20)],text:'Часть людей уходит и забирает свою долю.'},
    {ref:'group.exile',title:'Изгнание',type:'event',src:'gdd',gdd:'§23',source:'player',effects:[sub('group_size',1),add('world_danger',3)],
     text:'Изгнанный запомнит и может вернуться — один или с другими.'},
    {ref:'group.former_member_returns',title:'Ушедший вернулся',type:'choice',src:'gdd',gdd:'§21',source:'npc',
     text:'«Возвращать ранее ушедших членов».',
     choices:[ch('Принять обратно','group.ok',{effects:[add('group_size',1),add('group_tension',5)]}),ch('Прогнать','exploration.ok')]}
  ]
},
{
  id:'combat',title:'Бой, угрозы и шум',
  intro:'Угрозы реагируют на время суток, погоду, шум, следы и нехватку ресурсов (§22).',
  nodes:[
    {ref:'combat.ambush_on_road',title:'Засада на трассе',type:'choice',src:'gdd',gdd:'§21–22',source:'faction',refs:['loc_highway','f_raiders'],
     text:'Бой, бегство или откуп.',
     choices:[ch('Драться','health.injury_on_raid',{effects:[add('noise_level',20)]}),
              ch('Бежать','exploration.ok',{effects:[sub('shelter_food_days',1)]}),
              ch('Откупиться','exploration.ok',{effects:[sub('shelter_water',50)]}),
              ch('Сдаться','capture.player_captured')]},
    {ref:'combat.zombies_drawn_by_noise',title:'Шум привлёк зомби',type:'event',src:'gdd',gdd:'§22',source:'world',refs:['t_zombies'],
     trigger:when(c('noise_level','>=',40)),effects:[add('zombie_pressure',20),sub('noise_level',20)],
     text:'Взлом, выстрел или генератор — и к месту стягиваются зомби.',choices:[ch('Ночью у двери толпа','combat.night_horde')]},
    {ref:'combat.night_horde',title:'Толпа у убежища',type:'choice',src:'idea',source:'world',trigger:when(c('zombie_pressure','>=',60)),
     text:'Ночью у входа собирается толпа.',
     choices:[ch('Держать оборону','health.injury_on_raid',{effects:[sub('shelter_condition',10),sub('zombie_pressure',30)]}),
              ch('Затаиться и ждать','group.ok',{effects:[sub('group_morale',10),sub('zombie_pressure',15)]})]},
    {ref:'combat.raid_on_shelter',title:'Нападение на убежище',type:'choice',src:'gdd',gdd:'§21',source:'faction',
     trigger:when(c('shelter_known','==',1),c('rep_raiders','<=',-60)),text:'Потери, украденные запасы, повреждения.',
     choices:[ch('Отбились','health.injury_on_raid',{effects:[sub('shelter_condition',15),add('rep_raiders',-10)]}),
              ch('Не отбились','capture.member_captured',{effects:[sub('shelter_food_days',5),sub('shelter_water',150)]})]},
    {ref:'combat.watch_fight',title:'Чужой бой',type:'choice',src:'gdd',gdd:'§21',source:'faction',
     text:'Наблюдать, вмешаться или воспользоваться последствиями.',
     choices:[ch('Наблюдать','exploration.ok'),ch('Помочь слабым','health.injury_on_raid',{effects:[add('rep_community',15),sub('rep_raiders',15)]}),
              ch('Обобрать павших после','death.stranger_body_found',{effects:[sub('rep_community',5)]})]}
  ]
},
{
  id:'building',title:'Убежище как место',
  intro:'Механики (рецепты, прочность, нагрузка) описывают ОС и Object Plan. Здесь только события, которые из них вытекают (§14–16).',
  nodes:[
    {ref:'repair.equipment_breaks',title:'Сломалось оборудование',type:'choice',src:'gdd',gdd:'§15',source:'system',
     trigger:when(c('shelter_condition','<',50)),text:'Насос, фильтр или верстак. Ведёт к кризису воды или энергии.',
     choices:[ch('Починить своими силами','building.ok',{effects:[add('shelter_condition',15)]}),ch('Отложить','water.tank_leak')]},
    {ref:'building.ok',title:'Работает',type:'event',src:'idea',source:'system',text:'Оборудование в порядке.'},
    {ref:'physics.shelf_collapse',title:'Рухнула перегруженная полка',type:'event',src:'gdd',gdd:'§16',source:'system',
     trigger:every(24*16),effects:[sub('shelter_meds',1),sub('shelter_condition',3)],text:'Нагрузка + время → поломка → падение предметов.'},
    {ref:'building.expansion',title:'Расширили убежище',type:'event',src:'gdd',gdd:'§3.3',source:'player',
     effects:[add('shelter_condition',10),sub('shelter_energy',10),set('has_greenhouse',1)],text:'Новая комната (например, оранжерея). Больше места — больше потребление.'},
    {ref:'digging.found_cavity',title:'За стеной пустота',type:'choice',src:'idea',source:'location',
     text:'Копая, наткнулись на старый тоннель или чужой подвал. Новый путь — и для врагов тоже.',
     choices:[ch('Исследовать','exploration.other_bunker'),ch('Замуровать','building.ok')]},
    {ref:'light.dark_room_fear',title:'Тревога в темноте',type:'event',src:'idea',source:'system',effects:[sub('group_morale',5),add('group_tension',5)],
     text:'Без света в убежище растёт тревога.'},
    {ref:'crafting.first_tool',title:'Первый важный инструмент',type:'event',src:'gdd',gdd:'§14',source:'player',
     text:'Сделан первый инструмент или оружие — открываются новые действия на вылазках.'}
  ]
}
];

// Открытые вопросы — уходят в «Решения» Story Map и в MD.
const OPEN_QUESTIONS=[
  {title:'История катастрофы',text:'Что случилось с миром? Сколько лет прошло? Откуда зомби?'},
  {title:'Фракции',text:'Подтвердить архетипы (община, торговцы, рейдеры, работорговцы, остатки порядка, одиночки) или дать свои. Сколько в первой версии?'},
  {title:'Размер мира на старте',text:'Предложение: бункер + трасса + город (5–10 домов) + чужой бункер + лагерь фракции.'},
  {title:'Сезоны / зима',text:'Нужны ли? Сильно влияют на воду, еду и топливо.'},
  {title:'Фазы игры',text:'Мир «просыпается» постепенно (день 8 / 30 / 60) или живой с первого дня?'},
  {title:'Тон',text:'Где граница жёсткости: рабство, отравление воды, пытки пленных?'},
  {title:'Финал',text:'Нужны ли концовки, кроме гибели группы?'}
];

module.exports={VARIABLES,ENTITIES,RELATIONS,CATEGORIES,OPEN_QUESTIONS};
